USE [master]
GO

/****** Object:  Database [sd_test]    Script Date: 03/04/2013 06:00:44 ******/
CREATE DATABASE [sd_test] ON  PRIMARY 
( NAME = N'sd_test', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\sd_test.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'sd_test_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\sd_test_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [sd_test] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [sd_test].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [sd_test] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [sd_test] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [sd_test] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [sd_test] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [sd_test] SET ARITHABORT OFF 
GO

ALTER DATABASE [sd_test] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [sd_test] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [sd_test] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [sd_test] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [sd_test] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [sd_test] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [sd_test] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [sd_test] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [sd_test] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [sd_test] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [sd_test] SET  DISABLE_BROKER 
GO

ALTER DATABASE [sd_test] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [sd_test] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [sd_test] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [sd_test] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [sd_test] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [sd_test] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [sd_test] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [sd_test] SET  READ_WRITE 
GO

ALTER DATABASE [sd_test] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [sd_test] SET  MULTI_USER 
GO

ALTER DATABASE [sd_test] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [sd_test] SET DB_CHAINING OFF 
GO

