<?xml version="1.0" encoding="utf-8"?><Database Name="sd_test" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ALDERAMIN\SQLEXPRESS;Initial Catalog=sd_test;Integrated Security=True" SettingsObjectName="sd_final.Properties.Settings" SettingsPropertyName="sd_testConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.sd_cat" Member="sd_cats">
    <Type Name="sd_cat">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="sd_cat_sd_inc" Member="sd_incs" ThisKey="id" OtherKey="sd_cat_id" Type="sd_inc" />
    </Type>
  </Table>
  <Table Name="dbo.sd_history" Member="sd_histories">
    <Type Name="sd_history">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sd_user_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="action" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sd_inc_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="a_descr" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="sd_user_sd_history" Member="sd_user" ThisKey="sd_user_id" OtherKey="id" Type="sd_user" IsForeignKey="true" />
      <Association Name="sd_inc_sd_history" Member="sd_inc" ThisKey="sd_inc_id" OtherKey="id" Type="sd_inc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.sd_priv" Member="sd_privs">
    <Type Name="sd_priv">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="sd_priv_sd_user" Member="sd_users" ThisKey="id" OtherKey="priv" Type="sd_user" />
    </Type>
  </Table>
  <Table Name="dbo.sd_problem" Member="sd_problems">
    <Type Name="sd_problem">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="desigion" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="sd_problem_sd_inc" Member="sd_incs" ThisKey="id" OtherKey="sd_problem_id" Type="sd_inc" />
    </Type>
  </Table>
  <Table Name="dbo.sd_status" Member="sd_status">
    <Type Name="sd_status">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="sd_status_sd_inc" Member="sd_incs" ThisKey="id" OtherKey="sd_status_id" Type="sd_inc" />
    </Type>
  </Table>
  <Table Name="dbo.sd_users" Member="sd_users">
    <Type Name="sd_user">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fio" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="priv" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="sd_user_sd_history" Member="sd_histories" ThisKey="id" OtherKey="sd_user_id" Type="sd_history" />
      <Association Name="sd_user_sd_users_on_inc" Member="sd_users_on_incs" ThisKey="id" OtherKey="sd_user_id" Type="sd_users_on_inc" />
      <Association Name="sd_priv_sd_user" Member="sd_priv" ThisKey="priv" OtherKey="id" Type="sd_priv" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.sd_users_on_inc" Member="sd_users_on_incs">
    <Type Name="sd_users_on_inc">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sd_user_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="sd_inc_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="sd_user_sd_users_on_inc" Member="sd_user" ThisKey="sd_user_id" OtherKey="id" Type="sd_user" IsForeignKey="true" />
      <Association Name="sd_inc_sd_users_on_inc" Member="sd_inc" ThisKey="sd_inc_id" OtherKey="id" Type="sd_inc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.sd_inc" Member="sd_incs">
    <Type Name="sd_inc">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sd_status_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="reg_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="uinfo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="simptoms" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="sd_cat_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="res_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="close_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sd_problem_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="prior" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="des" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="desinfo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="sd_inc_sd_history" Member="sd_histories" ThisKey="id" OtherKey="sd_inc_id" Type="sd_history" />
      <Association Name="sd_inc_sd_users_on_inc" Member="sd_users_on_incs" ThisKey="id" OtherKey="sd_inc_id" Type="sd_users_on_inc" />
      <Association Name="sd_cat_sd_inc" Member="sd_cat" ThisKey="sd_cat_id" OtherKey="id" Type="sd_cat" IsForeignKey="true" />
      <Association Name="sd_problem_sd_inc" Member="sd_problem" ThisKey="sd_problem_id" OtherKey="id" Type="sd_problem" IsForeignKey="true" />
      <Association Name="sd_status_sd_inc" Member="sd_status" ThisKey="sd_status_id" OtherKey="id" Type="sd_status" IsForeignKey="true" />
    </Type>
  </Table>
</Database>